package com.example.tsngapp.helpers;

public enum ErrorCode {
    USERNAME_EMPTY,
    PASSWORD_EMPTY,
    NAME_EMPTY,
    EMAIL_EMPTY,
    PASSWORD_CONF_EMPTY,
    TYPE_UNDEFINED,
    PASSWORD_DONT_MATCH,
    ELDER_NAME_EMPTY,
    ELDER_BIRTH_DATE_EMPTY,
    ELDER_BIRTH_DATE_INVALID_FORMAT,
    ELDER_BIRTH_DATE_INAVLID_DATE,
    GENDER_UNDEFINED
}
